# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace

# Data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/etutor_datalog
    username: etutor_datalog
    password: secret
  jpa:
    show-sql: true

# Springdoc
springdoc:
  show-actuator: true

# Datalog
datalog:
  exe:
  maxExecutionTime: 10 # seconds
  factEncodingSuffix: 1
  doc-url: http://localhost:8080/api/forwardPublic/datalog/dlg/

# API key definition
clients:
  api-keys:
    - name: task-administration
      key: task-admin-key
      roles:
        - CRUD
        - SUBMIT
    - name: jobe-server
      key: jobe-server-key
      roles:
        - SUBMIT
    - name: plag-check
      key: plag-check-key
      roles:
        - READ_SUBMISSION
