# Logging
logging:
  level:
    ROOT: info

# Server
server:
  shutdown: GRACEFUL

# Springdoc
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Spring
spring:
  jpa:
    show-sql: false

# Specify the following settings via environment variables in the docker container.
## Database
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5434/etutor_datalog
#    username: etutor
#    password: TBD
#  flyway:
#    user: etutor_datalog_admin
#    password: TBD
#
## API key definition
#clients:
#  api-keys:
#    - name: task-administration
#      key: TBD
#      roles:
#       - CRUD
#       - SUBMIT
#    - name: jobe-server
#      key: TBD
#      roles:
#       - SUBMIT
#    - name: plag-check
#      key: TBD
#      roles:
#       - READ_SUBMISSION
## Datalog
#datalog:
#  exe: ./bin/dlv-mac-m1 # Adjust to your OS
#  maxExecutionTime: 10 # seconds
#  factEncodingSuffix: 0
#  doc-url: https://etutor.dke.uni-linz.ac.at/api/forwardPublic/datalog/dlg/
